linearSearch:
	gcc linearSearch.c test.c -o linearSearch

binarySearch:
	gcc binarySearch.c test.c -o binarySearch

binarySearchRecursive:
	gcc binarySearchRecursive.c test.c -o binarySearchRecursive
