euclidsAlgorithm:
	gcc euclidsAlgorithm.c test.c -o euclidsAlgorithm

middleSchool:
	gcc middleSchool.c test.c -o middleSchool

consecutiveInteger:
	gcc consecutiveInteger.c test.c -o consecutiveInteger

combined:
	gcc combined.c -o combined